"use strict";
exports.__esModule = true;
// import * as OurMath from './math';
var math_1 = require("./math");
// const r1 = OurMath.sum(42, 1);
// const r2 = OurMath.powerOf2(42);
// const r3 = OurMath.sub(42, 1);
var r4 = math_1["default"](42, 1);
// console.log(`Result of sum(42, 1) is ${r1}`);
// console.log(`Result of powerOf2(42) is ${r2}`);
// console.log(`Result of sub(42, 1) is ${r3}`);
console.log("Result of sum(41, 1) is " + r4);
